name:                Assignment5
version:             0.1.0.0
github:              "timothyakline/CS331_Assignment5"
license:             BSD3
author:              "Timothy Albert Kline"
maintainer:          "timothyalbertkline@gmail.com"
copyright:           "© 2021 Timothy Albert Kline. All rights reserved."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Haskell Stack project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/timothyakline/CS331_Assignment5#readme>

dependencies:
- base >= 4.7 && < 5

library:
  when:
    condition: false
    other-modules: Paths_Assignment5
  source-dirs: src

executables:
  Assignment5-exe:
    main:                pa5_test.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Assignment5

tests:
  Assignment5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Assignment5
